# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afb4d20ee1de0728ce6a8979553de50c576c7e1b7f8b096cfe9cfdd6050069ba77a6e55d01c9c171028888dcf4a58ecff30c969755413b1b2e429df8f23c616f

test:
  secret_key_base: 5b1b760bc75cd1f59decb1accfe414b9b23a8e5ab016510d15c7645ab00cff41ca055546307e47a1982459f5b5df7e54a7e0e8c60d772317d9e40b8362a9c5cb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
